### ISSUE TITLE
Support multiple specs in scripts

### ISSUE THREAD

**Issue by x1n13y84issmd42** [x1n13y84issmd42/oasis#30]
The ultimate goal of Oasis is testing of microservice solutions, and this requires support for multiple spec files referenced from scripts, with names.

The suggested approach follows.

Spec reference:
```yaml
specs:
  serviceA: path/to/serviceA.spec.yaml
  serviceB: path/to/serviceB.spec.yaml
  serviceC: path/to/serviceC.spec.yaml
```
Multiple spec files are listed with their names to use to access operations in them.

Operation reference:
```yaml
operations:
  operationFoo:
    operationId: serviceA.operationFooId
```
Operation ID includes a spec name from the `specs` object.
