### ISSUE TITLE
More parameter expression syntax improvements

### ISSUE THREAD

**Issue by x1n13y84issmd42** [x1n13y84issmd42/oasis#36]
Some APIs often need some special values as input, such as timestamps, IP addresses, random values of various formats.

Need to implement a way to have them as parameter values in scripts.

Something along the lines of

```
body:
  currentTime: "(timestamp())"
  myIP: "(IP())"
  randomString: (random.string())
```

The supposed list of potentially useful functions:

* timestamp() - current timestamp
* IP() - current IP address
* random.number(3, 105) - a random number in the range 3-105
* random.uuid() - a random UUID
